# Generated by Django 4.2.8 on 2023-12-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30, null=True, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('subyekt', models.TextField(blank=True, null=True, verbose_name='Subyekt')),
                ('xabar', models.TextField(null=True, verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontaktlar',
            },
        ),
    ]
