# Generated by Django 4.2.8 on 2024-01-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': "Kontakt ma'lumoti", 'verbose_name_plural': "Kontakt ma'lumotlari"},
        ),
    ]
