# Generated by Django 4.2.8 on 2024-01-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': "Post ma'lumoti ", 'verbose_name_plural': "Post ma'lumotlari "},
        ),
    ]
