# Generated by Django 4.2.8 on 2024-02-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='subyekt',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='nomer',
            field=models.TextField(blank=True, null=True, verbose_name='Nomer'),
        ),
    ]
