# Generated by Django 4.2.8 on 2024-02-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0005_delete_post_remove_contactmodel_subyekt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='nomer',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Nomer'),
        ),
    ]
